### PR TITLE
object spread/delete working

### PR DESCRIPTION
**Pull request by KoryNunn**
@MauriceButler

### CODE REVIEW

**Comment by MauriceButler** [comment]
Hrmmm seems very magic... :8ball: 

But also very useful... :+1: 

I think there is a glitch in the matrix...

**Comment by KoryNunn** [comment]
Déjà vu

**Comment by KoryNunn** [comment]
major bump?

**Comment by MauriceButler** [comment]
dosnt break api right? is new feature / functionality only I would minor

**Comment by KoryNunn** [comment]
https://github.com/KoryNunn/presh/commit/9136129ddd637f7bc112a5be6f8bba3afb0bf87e

**Pull request merged**
